<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ShareWith</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        .main {
            width: 400px;
            height: 200px;
            margin: 150px auto;
            text-align: center;
            padding: 50px 50px;
            border-radius: 10px;
        }
        .error {
            color: rgba(68, 67, 76, 0.649);
            font-family: 'Ubuntu', sans-serif;
            font-size: 2.5em;
            font-weight: 900;
            text-shadow: 2px 2px 3px rgba(44, 42, 42, 0.308);
            padding-left: 40px;
            padding-right: 40px;
        }
    </style>
</head>
<body>
    <div class="main">
        <span class="error"><p><?php echo $error; ?></p></span>
    </div>
</body>
</html>